### ISSUE TITLE
MTP usb mount not functioning.

### ISSUE THREAD

**Issue by poetaster** [HelloVolla/droid-config-halium-mimameid#1]
After a recent (usb charging fix?) update, MTP mounting no longer works. I tested using the same dock port with a Volla and xperia 10ii. Both devices mounted as expected. Settings were 'always ask' for usb connections.

**Comment by wurzer** [comment]
I'm afraid, this is the wrong board. Could you please post an issue either to https://github.com/HelloVolla/volla-os-beta-test or to https://github.com/HelloVolla/ubuntu-touch-beta-tests?

**Comment by poetaster** [comment]
Ah, it's specific to the halium-mimameid images ... which are neither vollaos nor ubuntu touch, but sailfish? I posted here because @piggz asked ?

**Comment by piggz** [comment]
This is where I would like sailfish bugs to be reported (i know this user, and its a sailfish issue) is that ok?

**Comment by wurzer** [comment]
@piggz Is this the Sailfish OS specific project? Looks like the generic Halium project for the device.

**Comment by piggz** [comment]
Yes its sailfish specific. its the package that contains all config, i named it this way because the sailfish port uses halium, the droid-config prefix is a standard term in sailfish ports.

**Comment by wurzer** [comment]
@piggz Thanks for clarification. Can you add a sentence to the readme file of this project about the scope?

**Comment by poetaster** [comment]
Now working for me on the last update.
